/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomerInfo {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    email: string;
    address: string;
    phone: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OrderItem {
    title: string;
    productId: string;
    quantity: bigint;
    price: bigint;
}
export interface CustomOrderRequest {
    id: string;
    inspirationImage: ExternalBlob;
    createdAt: Time;
    size: string;
    description: string;
    productType: string;
    email: string;
    colorPreference: string;
    budgetRange: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReturnRequest {
    id: string;
    createdAt: Time;
    description: string;
    email: string;
    orderId: string;
    reason: string;
}
export interface Order {
    id: string;
    customerInfo: CustomerInfo;
    status: string;
    total: bigint;
    createdAt: Time;
    items: Array<OrderItem>;
}
export interface Product {
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    category: string;
    image: ExternalBlob;
    price: bigint;
    bestseller: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    createCustomOrderRequest(request: CustomOrderRequest): Promise<void>;
    createOrder(order: Order): Promise<string>;
    createProduct(passcode: string, product: Product): Promise<void>;
    createReturnRequest(request: ReturnRequest): Promise<void>;
    deleteProduct(passcode: string, productId: string): Promise<void>;
    getCustomOrderRequests(passcode: string): Promise<Array<CustomOrderRequest>>;
    getOrderById(orderId: string): Promise<Order>;
    getOrders(passcode: string): Promise<Array<Order>>;
    getProductById(productId: string): Promise<Product>;
    getProducts(): Promise<Array<Product>>;
    getReturnRequests(passcode: string): Promise<Array<ReturnRequest>>;
    getSubscribers(passcode: string): Promise<Array<string>>;
    subscribeToNewsletter(email: string): Promise<void>;
    updateOrderStatus(passcode: string, orderId: string, status: string): Promise<void>;
    updateProduct(passcode: string, product: Product): Promise<void>;
}
import type { CustomOrderRequest as _CustomOrderRequest, ExternalBlob as _ExternalBlob, Product as _Product, Time as _Time, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async createCustomOrderRequest(arg0: CustomOrderRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomOrderRequest(await to_candid_CustomOrderRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomOrderRequest(await to_candid_CustomOrderRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReturnRequest(arg0: ReturnRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReturnRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReturnRequest(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0, arg1);
            return result;
        }
    }
    async getCustomOrderRequests(arg0: string): Promise<Array<CustomOrderRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomOrderRequests(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomOrderRequests(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return result;
        }
    }
    async getOrders(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders(arg0);
            return result;
        }
    }
    async getProductById(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_Product_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_Product_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReturnRequests(arg0: string): Promise<Array<ReturnRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturnRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturnRequests(arg0);
            return result;
        }
    }
    async getSubscribers(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscribers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscribers(arg0);
            return result;
        }
    }
    async subscribeToNewsletter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToNewsletter(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, await to_candid_Product_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_CustomOrderRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomOrderRequest): Promise<CustomOrderRequest> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Product_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inspirationImage: _ExternalBlob;
    createdAt: _Time;
    size: string;
    description: string;
    productType: string;
    email: string;
    colorPreference: string;
    budgetRange: string;
}): Promise<{
    id: string;
    inspirationImage: ExternalBlob;
    createdAt: Time;
    size: string;
    description: string;
    productType: string;
    email: string;
    colorPreference: string;
    budgetRange: string;
}> {
    return {
        id: value.id,
        inspirationImage: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.inspirationImage),
        createdAt: value.createdAt,
        size: value.size,
        description: value.description,
        productType: value.productType,
        email: value.email,
        colorPreference: value.colorPreference,
        budgetRange: value.budgetRange
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: _Time;
    description: string;
    category: string;
    image: _ExternalBlob;
    price: bigint;
    bestseller: boolean;
}): Promise<{
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    category: string;
    image: ExternalBlob;
    price: bigint;
    bestseller: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        image: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.image),
        price: value.price,
        bestseller: value.bestseller
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomOrderRequest>): Promise<Array<CustomOrderRequest>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CustomOrderRequest_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n17(_uploadFile, _downloadFile, x)));
}
async function to_candid_CustomOrderRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomOrderRequest): Promise<_CustomOrderRequest> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Product_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    category: string;
    image: ExternalBlob;
    price: bigint;
    bestseller: boolean;
}): Promise<{
    id: string;
    title: string;
    createdAt: _Time;
    description: string;
    category: string;
    image: _ExternalBlob;
    price: bigint;
    bestseller: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image),
        price: value.price,
        bestseller: value.bestseller
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inspirationImage: ExternalBlob;
    createdAt: Time;
    size: string;
    description: string;
    productType: string;
    email: string;
    colorPreference: string;
    budgetRange: string;
}): Promise<{
    id: string;
    inspirationImage: _ExternalBlob;
    createdAt: _Time;
    size: string;
    description: string;
    productType: string;
    email: string;
    colorPreference: string;
    budgetRange: string;
}> {
    return {
        id: value.id,
        inspirationImage: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.inspirationImage),
        createdAt: value.createdAt,
        size: value.size,
        description: value.description,
        productType: value.productType,
        email: value.email,
        colorPreference: value.colorPreference,
        budgetRange: value.budgetRange
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
