/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomOrderRequest {
  'id' : string,
  'inspirationImage' : ExternalBlob,
  'createdAt' : Time,
  'size' : string,
  'description' : string,
  'productType' : string,
  'email' : string,
  'colorPreference' : string,
  'budgetRange' : string,
}
export interface CustomerInfo {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'customerInfo' : CustomerInfo,
  'status' : string,
  'total' : bigint,
  'createdAt' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'title' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'bestseller' : boolean,
}
export interface ReturnRequest {
  'id' : string,
  'createdAt' : Time,
  'description' : string,
  'email' : string,
  'orderId' : string,
  'reason' : string,
}
export type Time = bigint;
export interface WishlistItem {
  'productId' : string,
  'email' : string,
  'addedAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addToWishlist' : ActorMethod<[string, string], undefined>,
  'createCustomOrderRequest' : ActorMethod<[CustomOrderRequest], undefined>,
  'createOrder' : ActorMethod<[Order], string>,
  'createProduct' : ActorMethod<[string, Product], undefined>,
  'createReturnRequest' : ActorMethod<[ReturnRequest], undefined>,
  'deleteProduct' : ActorMethod<[string, string], undefined>,
  'filterProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getBestSellers' : ActorMethod<[], Array<Product>>,
  'getCustomOrderRequests' : ActorMethod<[string], Array<CustomOrderRequest>>,
  'getOrderById' : ActorMethod<[string], Order>,
  'getOrders' : ActorMethod<[string], Array<Order>>,
  'getProductById' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReturnRequests' : ActorMethod<[string], Array<ReturnRequest>>,
  'getWishlist' : ActorMethod<[string], Array<WishlistItem>>,
  'removeFromWishlist' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string, string], undefined>,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];