/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const CustomOrderRequest = IDL.Record({
  'id' : IDL.Text,
  'inspirationImage' : ExternalBlob,
  'createdAt' : Time,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'colorPreference' : IDL.Text,
  'budgetRange' : IDL.Text,
});
export const CustomerInfo = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerInfo' : CustomerInfo,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'bestseller' : IDL.Bool,
});
export const ReturnRequest = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'orderId' : IDL.Text,
  'reason' : IDL.Text,
});
export const WishlistItem = IDL.Record({
  'productId' : IDL.Text,
  'email' : IDL.Text,
  'addedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addToWishlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCustomOrderRequest' : IDL.Func([CustomOrderRequest], [], []),
  'createOrder' : IDL.Func([Order], [IDL.Text], []),
  'createProduct' : IDL.Func([IDL.Text, Product], [], []),
  'createReturnRequest' : IDL.Func([ReturnRequest], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'filterProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], []),
  'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], []),
  'getCustomOrderRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomOrderRequest)],
      [],
    ),
  'getOrderById' : IDL.Func([IDL.Text], [Order], []),
  'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getProductById' : IDL.Func([IDL.Text], [Product], []),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
  'getReturnRequests' : IDL.Func([IDL.Text], [IDL.Vec(ReturnRequest)], []),
  'getWishlist' : IDL.Func([IDL.Text], [IDL.Vec(WishlistItem)], []),
  'removeFromWishlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const CustomOrderRequest = IDL.Record({
    'id' : IDL.Text,
    'inspirationImage' : ExternalBlob,
    'createdAt' : Time,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'colorPreference' : IDL.Text,
    'budgetRange' : IDL.Text,
  });
  const CustomerInfo = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerInfo' : CustomerInfo,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'bestseller' : IDL.Bool,
  });
  const ReturnRequest = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'orderId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const WishlistItem = IDL.Record({
    'productId' : IDL.Text,
    'email' : IDL.Text,
    'addedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addToWishlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCustomOrderRequest' : IDL.Func([CustomOrderRequest], [], []),
    'createOrder' : IDL.Func([Order], [IDL.Text], []),
    'createProduct' : IDL.Func([IDL.Text, Product], [], []),
    'createReturnRequest' : IDL.Func([ReturnRequest], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'filterProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], []),
    'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], []),
    'getCustomOrderRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomOrderRequest)],
        [],
      ),
    'getOrderById' : IDL.Func([IDL.Text], [Order], []),
    'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getProductById' : IDL.Func([IDL.Text], [Product], []),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], []),
    'getReturnRequests' : IDL.Func([IDL.Text], [IDL.Vec(ReturnRequest)], []),
    'getWishlist' : IDL.Func([IDL.Text], [IDL.Vec(WishlistItem)], []),
    'removeFromWishlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };