/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const CustomOrderRequest = IDL.Record({
  'id' : IDL.Text,
  'inspirationImage' : ExternalBlob,
  'createdAt' : Time,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'colorPreference' : IDL.Text,
  'budgetRange' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'country' : IDL.Text,
  'orderStatus' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'orderDate' : Time,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'shippingAddress' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
  'bestseller' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ReturnRequest = IDL.Record({
  'customerName' : IDL.Text,
  'video' : ExternalBlob,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'orderNumber' : IDL.Text,
  'reason' : IDL.Text,
});
export const WishlistItem = IDL.Record({
  'productId' : IDL.Text,
  'email' : IDL.Text,
  'addedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomOrderRequest' : IDL.Func([CustomOrderRequest], [], []),
  'createOrder' : IDL.Func([Order], [IDL.Text], []),
  'createProduct' : IDL.Func([Product], [], []),
  'createReturnRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCustomOrderRequests' : IDL.Func([], [IDL.Vec(CustomOrderRequest)], []),
  'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCategory' : IDL.Func([IDL.Text], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const CustomOrderRequest = IDL.Record({
    'id' : IDL.Text,
    'inspirationImage' : ExternalBlob,
    'createdAt' : Time,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'colorPreference' : IDL.Text,
    'budgetRange' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'country' : IDL.Text,
    'orderStatus' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'orderDate' : Time,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'shippingAddress' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
    'bestseller' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ReturnRequest = IDL.Record({
    'customerName' : IDL.Text,
    'video' : ExternalBlob,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'orderNumber' : IDL.Text,
    'reason' : IDL.Text,
  });
  const WishlistItem = IDL.Record({
    'productId' : IDL.Text,
    'email' : IDL.Text,
    'addedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomOrderRequest' : IDL.Func([CustomOrderRequest], [], []),
    'createOrder' : IDL.Func([Order], [IDL.Text], []),
    'createProduct' : IDL.Func([Product], [], []),
    'createReturnRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCustomOrderRequests' : IDL.Func([], [IDL.Vec(CustomOrderRequest)], []),
    'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCategory' : IDL.Func([IDL.Text], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };