/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomOrderRequest {
  'id' : string,
  'inspirationImage' : ExternalBlob,
  'createdAt' : Time,
  'size' : string,
  'description' : string,
  'productType' : string,
  'email' : string,
  'colorPreference' : string,
  'budgetRange' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'customerName' : string,
  'country' : string,
  'orderStatus' : string,
  'city' : string,
  'postalCode' : string,
  'orderDate' : Time,
  'email' : string,
  'state' : string,
  'shippingAddress' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'title' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
  'bestseller' : boolean,
}
export interface ReturnRequest {
  'customerName' : string,
  'video' : ExternalBlob,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
  'orderNumber' : string,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem {
  'productId' : string,
  'email' : string,
  'addedAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomOrderRequest' : ActorMethod<[CustomOrderRequest], undefined>,
  'createOrder' : ActorMethod<[Order], string>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'createReturnRequest' : ActorMethod<
    [string, string, string, string, string, ExternalBlob],
    undefined
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getCustomOrderRequests' : ActorMethod<[], Array<CustomOrderRequest>>,
  'getOrderById' : ActorMethod<[string], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[string], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReturnRequests' : ActorMethod<[], Array<ReturnRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCategory' : ActorMethod<[string], undefined>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];